### ISSUE TITLE
Cannot read property 'pipe' of undefined

### ISSUE THREAD

**Issue by hariramnandagopal** [jonathanasquier/stripe-pdf-invoice#1]
Hi ,

Thanks for the module. After integrating - i always endup in "Cannot read property 'pipe' of undefined" error.

This is what my code is 

res.set('content-type', 'application/pdf; charset=utf-8');
    pdfInvoice.generate(invoiceId, {number:"23233"}, function(error, pdfname, stream){
        //Force download
        //res.set('Content-Disposition', 'attachment; filename=' + pdfname + '.pdf');
        stream.pipe(res);

```
});
```

Let me know if i am doing anything wrong.

**Comment by jonathanasquier** [comment]
The module uses [wkhtmltopdf](https://www.npmjs.com/package/wkhtmltopdf) to generate the pdf, which gives a pdf stream in the callback. The wkhtmltopdf npm uses the wkhtmltopdf exec http://wkhtmltopdf.org/downloads.html
have you made sure it's installed? :)
(I'll add it in the readme)

**Comment by hariramnandagopal** [comment]
Yeah , I have installed the module using "npm install wkhtmltopdf" and try it again. Still no luck and I am getting the same error. Whether we need to call the wkhtmltopdf module before the "require("stripe-pdf-invoice") ?

**Comment by jonathanasquier** [comment]
Yes, but there is also the  wkhtmltopdf executable to install on your machine
http://wkhtmltopdf.org/downloads.html
make sure it's in your PATH an that you can reach it typing wkhtmltopdf in a terminal

**Comment by jonathanasquier** [comment]
Please feel free to reopen if it doesn't fix it.
