### ISSUE TITLE
Invalid API Key

### ISSUE THREAD

**Issue by pmg1407** [jonathanasquier/stripe-pdf-invoice#10]
How to generate the stripekey, if i give a sample string it shows invalid API key provided.

**Comment by jonathanasquier** [comment]
Hi, you must [create a Stripe account](https://dashboard.stripe.com/register) and connect to the dashboard. Then on the left panel go to [Developers > API keys](https://dashboard.stripe.com/account/apikeys) to access you public and private keys.
You can toggle the "view test data" checkbox to get access to test keys.
Grab the secret key to use it with the module.

Please reopen if needed.
