### ISSUE TITLE
wkhtmltopdf command not found

### ISSUE THREAD

**Issue by mritgupta** [jonathanasquier/stripe-pdf-invoice#13]
I am using the example code. 

Node version:- 12.8.0
Npm version:- 6.10.2

**Comment by jonathanasquier** [comment]
Hello, you are supposed to install the [wkhtmltopdf executable](https://wkhtmltopdf.org/downloads.html).
It must be available in your path

**Comment by mritgupta** [comment]
Thanks, @jonathanasquier 
Now it starts working
