### ISSUE TITLE
currency_position_before boolean default value correction

### ISSUE THREAD

**Issue by eole1712** [jonathanasquier/stripe-pdf-invoice#2]
Hi guys.

I have a problem when I try to set currency_position_before to false.

index.js | ligne 64 =>
`invoice.currency_position_before = invoice.currency_position_before || true;`
It's always true (false || true = true)

Maybe we should replace by
`if (!invoice.hasOwnProperty('currency_position_before')) invoice.currency_position_before = true;
`

Tell me if I should PR to fix it.

**Comment by jonathanasquier** [comment]
Yes please feel free to PR :)

**Comment by jonathanasquier** [comment]
Done
