### ISSUE TITLE
Issue with pointing to local Stripe library

### ISSUE THREAD

**Issue by GethylRocketLab** [jonathanasquier/stripe-pdf-invoice#7]
Hi, 

Thanks for creating this package!

Though you have made changes in github to stop pointing to your local stripe file, it seems you haven't published it to `npm`?

- When I download the package from npm, 
<img width="293" alt="screen shot 2018-02-01 at 1 11 35 pm" src="https://user-images.githubusercontent.com/29849626/35657615-75855298-0751-11e8-861f-e4364af7c617.png">

- But if I download it from github directly, it imports the right package. 

Could you please push the changes to npm? 

## Actual Result:
PDF generated with hardcoded invoice values.
<img width="706" alt="screen shot 2018-02-01 at 1 14 50 pm" src="https://user-images.githubusercontent.com/29849626/35657698-ed969c06-0751-11e8-97b5-54cf29025594.png">

## Expected Result:
PDF to be generated by pulling the correct invoice details from Stripe.

**Comment by jonathanasquier** [comment]
I just published 2.0.3, please feel free to reopen if the issue still occurs.
Sorry for the inconvenience

**Comment by GethylRocketLab** [comment]
Thank you for the prompt action, it is good now :-)
